### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by CWYuan08** [vals/python-gprofiler#7]
Hi there,
when I tried with pip install gprofiler, it says: "Collecting gprofiler
  Could not find a version that satisfies the requirement gprofiler (from versions: )
No matching distribution found for grofiler" 
How should I install it?

Thank you 
Ulrika

**Comment by vals** [comment]
Hi Ulrika,

I just tried uninstalling and installing again with `pip install gprofiler`.

Was there no other information in the error message?

One thought: I'm not sure it works on Python 2. Which version of Python are you using?

Best,
/Valentine

**Comment by CWYuan08** [comment]
Hi @vals,
I am using Python 2.7.15.  Managed to install it. 

Thank you
Ulrika

**Comment by vals** [comment]
Ok, great!

Best,
/Valentine
